services:
  database:
    image: postgres
    container_name: loopt
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=todo
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root -d todo']
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  api:
    build: .
    container_name: loopt-api
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - JWT_SECRET=your_jwt_secret
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=todo
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - PORT=3000
    ports:
      - '3000:3000'
    command: ['node', 'dist/main.js']
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:3000/api']
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    build: .
    container_name: loopt-worker
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - JWT_SECRET=your_jwt_secret
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=todo
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - PORT=3000
    command: ['node', 'dist/modules/notification/notification.worker.js']
